// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: GymkhanaTimer

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_Label35;
extern void ui_event_Dropdown1(lv_event_t * e);
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_ListContainer2;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_ListContainer;
extern lv_obj_t * ui_Keyboard2;
extern lv_obj_t * ui_Label2;
extern void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label27;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label28;
extern void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label29;
extern void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label30;
extern void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label31;
extern void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Label36;
extern void ui_event_TextArea3(lv_event_t * e);
extern lv_obj_t * ui_TextArea3;
extern void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui_Label12;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label16;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label4;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_uiLabelCurrentTime;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Label39;
extern void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_uiLabelMCTime;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label43;
extern void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label44;
extern void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Roller7;
extern lv_obj_t * ui_Roller6;
extern lv_obj_t * ui_Roller8;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_Roller9;
extern lv_obj_t * ui_Roller10;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label45;
extern void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Label40;
extern void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Roller2;
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_Roller3;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Roller4;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Roller5;
extern lv_obj_t * ui_MasterRow1;
extern lv_obj_t * ui_ResultRow1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Roller2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

