// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: GymkhanaTimer

#include "../ui.h"

// COMPONENT MasterRow

lv_obj_t * ui_MasterRow_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_MasterRow;
    cui_MasterRow = lv_obj_create(comp_parent);
    lv_obj_set_height(cui_MasterRow, 30);
    lv_obj_set_width(cui_MasterRow, lv_pct(100));
    lv_obj_set_x(cui_MasterRow, -155);
    lv_obj_set_y(cui_MasterRow, -117);
    lv_obj_set_align(cui_MasterRow, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(cui_MasterRow, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_MasterRow, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(cui_MasterRow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_MasterRow, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_MasterRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_MasterRow, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_MasterRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_MasterRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_MasterRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_MasterRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_MasterRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(cui_MasterRow, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_MasterRow, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_MasterRow, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_MasterRow, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    lv_obj_t * cui_MasterRow1Rank;
    cui_MasterRow1Rank = lv_label_create(cui_MasterRow);
    lv_obj_set_width(cui_MasterRow1Rank, 60);
    lv_obj_set_height(cui_MasterRow1Rank, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_MasterRow1Rank, -349);
    lv_obj_set_y(cui_MasterRow1Rank, -141);
    lv_obj_set_align(cui_MasterRow1Rank, LV_ALIGN_CENTER);
    lv_label_set_text(cui_MasterRow1Rank, "Rank");
    lv_obj_set_style_text_color(cui_MasterRow1Rank, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_MasterRow1Rank, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_MasterRow1Rank, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_MasterRow1Rank, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_MasterRow1Rank, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_MasterRow1Rank, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_MasterRow1Class;
    cui_MasterRow1Class = lv_label_create(cui_MasterRow);
    lv_obj_set_width(cui_MasterRow1Class, 60);
    lv_obj_set_height(cui_MasterRow1Class, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_MasterRow1Class, -349);
    lv_obj_set_y(cui_MasterRow1Class, -141);
    lv_obj_set_align(cui_MasterRow1Class, LV_ALIGN_CENTER);
    lv_label_set_text(cui_MasterRow1Class, "Class");
    lv_obj_set_style_text_color(cui_MasterRow1Class, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_MasterRow1Class, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_MasterRow1Class, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_MasterRow1Class, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_MasterRow1Class, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_MasterRow1Class, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_MasterRow1No;
    cui_MasterRow1No = lv_label_create(cui_MasterRow);
    lv_obj_set_width(cui_MasterRow1No, 60);
    lv_obj_set_height(cui_MasterRow1No, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_MasterRow1No, -349);
    lv_obj_set_y(cui_MasterRow1No, -141);
    lv_obj_set_align(cui_MasterRow1No, LV_ALIGN_CENTER);
    lv_label_set_text(cui_MasterRow1No, "Axxx");
    lv_obj_set_style_text_color(cui_MasterRow1No, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_MasterRow1No, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_MasterRow1No, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_MasterRow1No, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_MasterRow1No, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_MasterRow1No, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_MasterRow1Name;
    cui_MasterRow1Name = lv_label_create(cui_MasterRow);
    lv_obj_set_width(cui_MasterRow1Name, 145);
    lv_obj_set_height(cui_MasterRow1Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_MasterRow1Name, -349);
    lv_obj_set_y(cui_MasterRow1Name, -141);
    lv_obj_set_align(cui_MasterRow1Name, LV_ALIGN_CENTER);
    lv_label_set_text(cui_MasterRow1Name, "Namexxxxxxxxx");
    lv_obj_set_style_text_color(cui_MasterRow1Name, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_MasterRow1Name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_MasterRow1Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_MasterRow1Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_MasterRow1Name, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_MasterRow1Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_MasterRow1Time;
    cui_MasterRow1Time = lv_label_create(cui_MasterRow);
    lv_obj_set_width(cui_MasterRow1Time, 80);
    lv_obj_set_height(cui_MasterRow1Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_MasterRow1Time, -349);
    lv_obj_set_y(cui_MasterRow1Time, -141);
    lv_obj_set_align(cui_MasterRow1Time, LV_ALIGN_CENTER);
    lv_label_set_text(cui_MasterRow1Time, "xx:xx.xxx");
    lv_obj_set_style_text_color(cui_MasterRow1Time, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_MasterRow1Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_MasterRow1Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_MasterRow1Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_MasterRow1Time, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_MasterRow1Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_MasterRow1React;
    cui_MasterRow1React = lv_label_create(cui_MasterRow);
    lv_obj_set_width(cui_MasterRow1React, 80);
    lv_obj_set_height(cui_MasterRow1React, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_MasterRow1React, -349);
    lv_obj_set_y(cui_MasterRow1React, -141);
    lv_obj_set_align(cui_MasterRow1React, LV_ALIGN_CENTER);
    lv_label_set_text(cui_MasterRow1React, "xx:xx.xxx");
    lv_obj_set_style_text_color(cui_MasterRow1React, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_MasterRow1React, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_MasterRow1React, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_MasterRow1React, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_MasterRow1React, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_MasterRow1React, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_MasterRow1PenMemo;
    cui_MasterRow1PenMemo = lv_label_create(cui_MasterRow);
    lv_obj_set_width(cui_MasterRow1PenMemo, 120);
    lv_obj_set_height(cui_MasterRow1PenMemo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_MasterRow1PenMemo, -349);
    lv_obj_set_y(cui_MasterRow1PenMemo, -141);
    lv_obj_set_align(cui_MasterRow1PenMemo, LV_ALIGN_CENTER);
    lv_label_set_text(cui_MasterRow1PenMemo, "Pen +1sec");
    lv_obj_set_style_text_color(cui_MasterRow1PenMemo, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_MasterRow1PenMemo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_MasterRow1PenMemo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_MasterRow1PenMemo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_MasterRow1PenMemo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_MasterRow1PenMemo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_MASTERROW_NUM);
    children[UI_COMP_MASTERROW_MASTERROW] = cui_MasterRow;
    children[UI_COMP_MASTERROW_MASTERROW1RANK] = cui_MasterRow1Rank;
    children[UI_COMP_MASTERROW_MASTERROW1CLASS] = cui_MasterRow1Class;
    children[UI_COMP_MASTERROW_MASTERROW1NO] = cui_MasterRow1No;
    children[UI_COMP_MASTERROW_MASTERROW1NAME] = cui_MasterRow1Name;
    children[UI_COMP_MASTERROW_MASTERROW1TIME] = cui_MasterRow1Time;
    children[UI_COMP_MASTERROW_MASTERROW1REACT] = cui_MasterRow1React;
    children[UI_COMP_MASTERROW_MASTERROW1PENMEMO] = cui_MasterRow1PenMemo;
    lv_obj_add_event_cb(cui_MasterRow, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_MasterRow, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_MasterRow_create_hook(cui_MasterRow);
    return cui_MasterRow;
}

