// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: GymkhanaTimer

#ifndef _UI_COMP_MASTERROW_H
#define _UI_COMP_MASTERROW_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT MasterRow
#define UI_COMP_MASTERROW_MASTERROW 0
#define UI_COMP_MASTERROW_MASTERROW1RANK 1
#define UI_COMP_MASTERROW_MASTERROW1CLASS 2
#define UI_COMP_MASTERROW_MASTERROW1NO 3
#define UI_COMP_MASTERROW_MASTERROW1NAME 4
#define UI_COMP_MASTERROW_MASTERROW1TIME 5
#define UI_COMP_MASTERROW_MASTERROW1REACT 6
#define UI_COMP_MASTERROW_MASTERROW1PENMEMO 7
#define _UI_COMP_MASTERROW_NUM 8
lv_obj_t * ui_MasterRow_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
