// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: GymkhanaTimer

#ifndef _GYMKHANATIMER_UI_COMP_HOOK_H
#define _GYMKHANATIMER_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_MasterRow_create_hook(lv_obj_t * comp);
void ui_comp_ResultRow_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
