// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: GymkhanaTimer

#ifndef _UI_COMP_RESULTROW_H
#define _UI_COMP_RESULTROW_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ResultRow
#define UI_COMP_RESULTROW_RESULTROW 0
#define UI_COMP_RESULTROW_RESULTROW1RANK 1
#define UI_COMP_RESULTROW_RESULTROW1CLASS 2
#define UI_COMP_RESULTROW_RESULTROW1NO 3
#define UI_COMP_RESULTROW_RESULTROW1NAME 4
#define UI_COMP_RESULTROW_RESULTROW1TIME 5
#define UI_COMP_RESULTROW_RESULTROW1TOP 6
#define UI_COMP_RESULTROW_RESULTROW1REACT 7
#define UI_COMP_RESULTROW_RESULTROW1PENMEMO 8
#define _UI_COMP_RESULTROW_NUM 9
lv_obj_t * ui_ResultRow_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
