// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: GymkhanaTimer

#include "../ui.h"

// COMPONENT ResultRow

lv_obj_t * ui_ResultRow_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ResultRow;
    cui_ResultRow = lv_obj_create(comp_parent);
    lv_obj_set_height(cui_ResultRow, 30);
    lv_obj_set_width(cui_ResultRow, lv_pct(100));
    lv_obj_set_x(cui_ResultRow, -155);
    lv_obj_set_y(cui_ResultRow, -117);
    lv_obj_set_align(cui_ResultRow, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(cui_ResultRow, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_ResultRow, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(cui_ResultRow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_ResultRow, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ResultRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_ResultRow, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_ResultRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_ResultRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_ResultRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_ResultRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_ResultRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(cui_ResultRow, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_ResultRow, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_ResultRow, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_ResultRow, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    lv_obj_t * cui_ResultRow1Rank;
    cui_ResultRow1Rank = lv_label_create(cui_ResultRow);
    lv_obj_set_width(cui_ResultRow1Rank, 60);
    lv_obj_set_height(cui_ResultRow1Rank, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_ResultRow1Rank, -349);
    lv_obj_set_y(cui_ResultRow1Rank, -141);
    lv_obj_set_align(cui_ResultRow1Rank, LV_ALIGN_CENTER);
    lv_label_set_text(cui_ResultRow1Rank, "Rank");
    lv_obj_set_style_text_color(cui_ResultRow1Rank, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_ResultRow1Rank, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_ResultRow1Rank, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_ResultRow1Rank, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_ResultRow1Rank, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_ResultRow1Rank, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ResultRow1Class;
    cui_ResultRow1Class = lv_label_create(cui_ResultRow);
    lv_obj_set_width(cui_ResultRow1Class, 60);
    lv_obj_set_height(cui_ResultRow1Class, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_ResultRow1Class, -349);
    lv_obj_set_y(cui_ResultRow1Class, -141);
    lv_obj_set_align(cui_ResultRow1Class, LV_ALIGN_CENTER);
    lv_label_set_text(cui_ResultRow1Class, "Class");
    lv_obj_set_style_text_color(cui_ResultRow1Class, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_ResultRow1Class, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_ResultRow1Class, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_ResultRow1Class, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_ResultRow1Class, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_ResultRow1Class, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ResultRow1No;
    cui_ResultRow1No = lv_label_create(cui_ResultRow);
    lv_obj_set_width(cui_ResultRow1No, 60);
    lv_obj_set_height(cui_ResultRow1No, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_ResultRow1No, -349);
    lv_obj_set_y(cui_ResultRow1No, -141);
    lv_obj_set_align(cui_ResultRow1No, LV_ALIGN_CENTER);
    lv_label_set_text(cui_ResultRow1No, "Axxx");
    lv_obj_set_style_text_color(cui_ResultRow1No, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_ResultRow1No, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_ResultRow1No, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_ResultRow1No, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_ResultRow1No, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_ResultRow1No, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ResultRow1Name;
    cui_ResultRow1Name = lv_label_create(cui_ResultRow);
    lv_obj_set_width(cui_ResultRow1Name, 145);
    lv_obj_set_height(cui_ResultRow1Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_ResultRow1Name, -349);
    lv_obj_set_y(cui_ResultRow1Name, -141);
    lv_obj_set_align(cui_ResultRow1Name, LV_ALIGN_CENTER);
    lv_label_set_text(cui_ResultRow1Name, "Namexxxxxxxxx");
    lv_obj_set_style_text_color(cui_ResultRow1Name, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_ResultRow1Name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_ResultRow1Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_ResultRow1Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_ResultRow1Name, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_ResultRow1Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ResultRow1Time;
    cui_ResultRow1Time = lv_label_create(cui_ResultRow);
    lv_obj_set_width(cui_ResultRow1Time, 80);
    lv_obj_set_height(cui_ResultRow1Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_ResultRow1Time, -349);
    lv_obj_set_y(cui_ResultRow1Time, -141);
    lv_obj_set_align(cui_ResultRow1Time, LV_ALIGN_CENTER);
    lv_label_set_text(cui_ResultRow1Time, "xx:xx.xxx");
    lv_obj_set_style_text_color(cui_ResultRow1Time, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_ResultRow1Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_ResultRow1Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_ResultRow1Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_ResultRow1Time, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_ResultRow1Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ResultRow1Top;
    cui_ResultRow1Top = lv_label_create(cui_ResultRow);
    lv_obj_set_width(cui_ResultRow1Top, 60);
    lv_obj_set_height(cui_ResultRow1Top, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_ResultRow1Top, -349);
    lv_obj_set_y(cui_ResultRow1Top, -141);
    lv_obj_set_align(cui_ResultRow1Top, LV_ALIGN_CENTER);
    lv_label_set_text(cui_ResultRow1Top, "Top%");
    lv_obj_set_style_text_color(cui_ResultRow1Top, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_ResultRow1Top, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_ResultRow1Top, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_ResultRow1Top, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_ResultRow1Top, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_ResultRow1Top, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ResultRow1React;
    cui_ResultRow1React = lv_label_create(cui_ResultRow);
    lv_obj_set_width(cui_ResultRow1React, 80);
    lv_obj_set_height(cui_ResultRow1React, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_ResultRow1React, -349);
    lv_obj_set_y(cui_ResultRow1React, -141);
    lv_obj_set_align(cui_ResultRow1React, LV_ALIGN_CENTER);
    lv_label_set_text(cui_ResultRow1React, "xx:xx.xxx");
    lv_obj_set_style_text_color(cui_ResultRow1React, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_ResultRow1React, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_ResultRow1React, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_ResultRow1React, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_ResultRow1React, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_ResultRow1React, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ResultRow1PenMemo;
    cui_ResultRow1PenMemo = lv_label_create(cui_ResultRow);
    lv_obj_set_width(cui_ResultRow1PenMemo, 120);
    lv_obj_set_height(cui_ResultRow1PenMemo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_ResultRow1PenMemo, -349);
    lv_obj_set_y(cui_ResultRow1PenMemo, -141);
    lv_obj_set_align(cui_ResultRow1PenMemo, LV_ALIGN_CENTER);
    lv_label_set_text(cui_ResultRow1PenMemo, "Pen +1sec");
    lv_obj_set_style_text_color(cui_ResultRow1PenMemo, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_ResultRow1PenMemo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_ResultRow1PenMemo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_ResultRow1PenMemo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_ResultRow1PenMemo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_ResultRow1PenMemo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_RESULTROW_NUM);
    children[UI_COMP_RESULTROW_RESULTROW] = cui_ResultRow;
    children[UI_COMP_RESULTROW_RESULTROW1RANK] = cui_ResultRow1Rank;
    children[UI_COMP_RESULTROW_RESULTROW1CLASS] = cui_ResultRow1Class;
    children[UI_COMP_RESULTROW_RESULTROW1NO] = cui_ResultRow1No;
    children[UI_COMP_RESULTROW_RESULTROW1NAME] = cui_ResultRow1Name;
    children[UI_COMP_RESULTROW_RESULTROW1TIME] = cui_ResultRow1Time;
    children[UI_COMP_RESULTROW_RESULTROW1TOP] = cui_ResultRow1Top;
    children[UI_COMP_RESULTROW_RESULTROW1REACT] = cui_ResultRow1React;
    children[UI_COMP_RESULTROW_RESULTROW1PENMEMO] = cui_ResultRow1PenMemo;
    lv_obj_add_event_cb(cui_ResultRow, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ResultRow, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_ResultRow_create_hook(cui_ResultRow);
    return cui_ResultRow;
}

