// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: GymkhanaTimer

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void on_class_filter_changed(lv_event_t * e);
void on_ta_focused(lv_event_t * e);
void on_set_clicked(lv_event_t * e);
void on_pt_clear_clicked(lv_event_t * e);
void on_pt_add_clicked(lv_event_t * e);
void on_mc_clicked(lv_event_t * e);
void on_dialog_ok(lv_event_t * e);
void on_dialog_cancel(lv_event_t * e);
void on_import_clicked(lv_event_t * e);
void on_start_clicked(lv_event_t * e);
void on_goal_clicked(lv_event_t * e);
void on_export_clicked(lv_event_t * e);
void on_set_time_clicked(lv_event_t * e);
void on_time_dialog_ok(lv_event_t * e);
void on_time_dialog_cancel(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
