; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:advance-hmi]
platform = https://github.com/Jason2866/platform-espressif32.git
board = ESP32-S3-WROOM-1-N16R8
framework = arduino
monitor_speed = 115200
board_upload.flash_size = 16MB
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
build_flags = 
	-DCONFIG_SPIRAM_SPEED_120M=
	-D LV_CONF_INCLUDE_SIMPLE
	-I src
	-I include
lib_deps = 
	lvgl/lvgl@8.3.11
	lovyan03/LovyanGFX@1.2.19
	adafruit/Adafruit SSD1306@2.5.13
	tamctec/TAMC_GT911@^1.0.2
	robtillaart/TCA9554@0.1.1
	adafruit/Adafruit BusIO@1.17.0
	bblanchon/ArduinoJson @ ^6.21.3
	adafruit/RTClib
	FS
	LittleFS
	WiFiClientSecure
